{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.29b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-tornado-{{ version }}.tar.gz
  sha256: 0fb18a71ed7c305335fe7009095cfca6e3bc0b034d285f360d5d78902acb05a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.29b0
    - opentelemetry-semantic-conventions ==0.29b0
    - opentelemetry-util-http ==0.29b0
    - python >=3.6
    # - tornado >=6.0
    # - opentelemetry-test ==0.24b0
    # - tornado >=6.0
    # - opentelemetry-test-utils ==0.26b1
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.27b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.28b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.28b1
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.29b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.29b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
