{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.64b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_tornado-{{ version }}.tar.gz
  sha256: a5f4da8a626859dc509529312f6478de8a6db572345d95e578ab9533f8a0dd58

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.64b0
    - opentelemetry-semantic-conventions ==0.64b0
    - opentelemetry-util-http ==0.64b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  description: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  doc_url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/tornado/tornado.html

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
  skip-lints:
    - documentation_specifies_language
