{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.30b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-tornado-{{ version }}.tar.gz
  sha256: 33b60a9896159594035d8aaef51db2f69a0997b078bfefc4a9b0ab275e0269f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b0
    - opentelemetry-semantic-conventions ==0.30b0
    - opentelemetry-util-http ==0.30b0
    - python >=3.6
    # - tornado >=6.0
    # - opentelemetry-test ==0.24b0
    # - tornado >=6.0
    # - opentelemetry-test-utils ==0.26b1
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.27b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.28b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.28b1
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.29b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.29b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.30b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
