{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-tornado-{{ version }}.tar.gz
  sha256: 6399c2846253acb7f6c5a8ee1fb8748af1e0931113b29ef49566c251f10fbb8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-semantic-conventions ==0.26b1
    - opentelemetry-util-http ==0.26b1
    - python >=3.6
    # - tornado >=6.0
    # - opentelemetry-test ==0.24b0
    # - tornado >=6.0
    # - opentelemetry-test-utils ==0.26b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
